---

- name: preset vm for ovirt-engine
  hosts: all
  vars_files:
    - vars/conf_vars.yml

  tasks:
    - name: set /etc/hosts file
      template:
        src: templates/hosts.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: 0644   
 
    - name: install lvm, firewalld, dnsmasq, nfs-utils and targetcli
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - dnsmasq
        - targetcli
        - lvm2
        - nfs-utils
        - firewalld
        - NetworkManager
    
    - name: Disable NetworkManager
      service:
        name: NetworkManager
        enabled: no
    - name: Enabled and start network
      service:
        name: network
        state: started
        enabled: yes

    - name: update dnsmasq config
      template:
        src: templates/dnsmasq.conf.j2
        dest: /etc/dnsmasq.conf
        owner: root
        group: root
        mode: 0644

    - name: start and enable dnsmasq
      service:
        name: dnsmasq
        state: started
        enabled: yes
    - name: update resolv.conf
      copy:
        content: nameserver 127.0.0.1
        dest: /etc/resolv.conf
       
    - name: vg1 setup
      lvg:
        vg: "{{ vg1_name }}"
        pvs: "{{ pv1_name }}"
    - name: lv setup
      lvol: 
        vg: "{{ vg1_name }}"
        lv: "{{ lv1_name }}"
        size: 19G

    - name: vg2 setup
      lvg:
        vg: "{{ vg2_name }}"
        pvs: "{{ pv2_name }}"
    - name: lv setup
      lvol: 
        vg: "{{ vg2_name }}"
        lv: "{{ lv2_name }}"
        size: 19G

    - name: Set lvm configuration
      template:
        src: templates/lvm.conf.j2
        dest: /etc/lvm/lvm.conf
        owner: root
        group: root
        mode: 0644

    - name: Create fs for export1
      filesystem:
        fstype: ext4
        dev: "/dev/{{ vg1_name }}/{{ lv1_name }}"

    - name: Create mount point for export1
      file:
        path: /exports
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Mount export1 fs
      mount:
        name: /exports
        src: "/dev/{{ vg1_name }}/{{ lv1_name }}"
        fstype: ext4
        state: mounted

    - name: Set iscsi configuration
      template:
        src: templates/saveconfig.json.j2
        dest: /etc/target/saveconfig.json
        owner: root
        group: root
        mode: 0644

    - name: Start and enabled targetcli
      service:
        name: target
        state: started
        enabled: yes

    - name: Start and enable nfs service
      service:
        name: nfs-server
        state: started
        enabled: yes

    - name: start and enabled firewalld
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: opens ports on firewall
      firewalld:
        service: "{{ item }}"
        state: enabled
        permanent: true
        immediate: true
      with_items:
        - ssh
        - https
        - dns
        - nfs

    - name: opens port for iscsi
      firewalld:
        port: 3260/tcp
        state: enabled
        permanent: true
        immediate: true
   
